% Export_latex_tables.m
%
% Builds .tex files for Tables 1, 2, C.7, D1, D2, and D3.
%
% Inputs:
%
%   code/model/heterogeneous/Results_counterfactuals/Counterfactual_heterogeneous_open.mat
%   code/model/heterogeneous/Results_counterfactuals/Counterfactual_heterogeneous_closed.mat
%   code/model/homogeneous/Results_counterfactuals/Counterfactual_homogeneous_open.mat
%   code/model/homogeneous/Results_counterfactuals/Counterfactual_homogeneous_closed.mat
%   code/model/policies/Counterfactual_to_compare_policies_{basef,top10,bottom_onlyt,top_onlyt,nobasef}.mat
%   code/model/heterogeneous/Setup_PP.m + Calibration_Res.m  (Table 1 and C.7)
%
% Outputs:
%
%   output/tables/table1.tex
%   output/tables/table2.tex
%   output/tables/tableC7.tex
%   output/tables/tableD1.tex
%   output/tables/tableD2.tex
%   output/tables/tableD3.tex
%   output/tables/sec61_aggregates.tex
%   output/tables/sec61_dollar_gains.tex
%   output/tables/sec63_decomposition.tex

% --- Resolve paths ---

this_file = mfilename('fullpath');
[code_dir, ~, ~] = fileparts(this_file);    
[code_root, ~, ~] = fileparts(code_dir);    
[pkg_root, ~, ~]  = fileparts(code_root);   

tables_out = fullfile(pkg_root, 'output', 'tables');
if ~exist(tables_out, 'dir'); mkdir(tables_out); end

% Calibration moments + parameter values (Sec 5.4, App C) 

[Mom_Model, Mom_Data, PP_cal] = snapshot_calibration(pkg_root);

% Helper: load a Tab xlsx with row names

load_agg = @(f) readtable(f, 'ReadRowNames', true);

% Load the 4 main scripts

h_open   = build_h_open_from_mat(fullfile(pkg_root, ...
                'code/model/heterogeneous/Results_counterfactuals/Counterfactual_heterogeneous_open.mat'));
h_closed = build_h_closed_from_mat(fullfile(pkg_root, ...
                'code/model/heterogeneous/Results_counterfactuals/Counterfactual_heterogeneous_closed.mat'));
m_open   = build_m_open_from_mat(fullfile(pkg_root, ...
                'code/model/homogeneous/Results_counterfactuals/Counterfactual_homogeneous_open.mat'));
m_closed = build_m_closed_from_mat(fullfile(pkg_root, ...
                'code/model/homogeneous/Results_counterfactuals/Counterfactual_homogeneous_closed.mat'));

% Load the 5 policy variants 

pol_dir = fullfile(pkg_root, 'code/model/policies/Results_counterfactuals');
p_basef     = build_p_from_mat(fullfile(pol_dir, 'Counterfactual_to_compare_policies_basef.mat'));
p_top10     = build_p_from_mat(fullfile(pol_dir, 'Counterfactual_to_compare_policies_top10.mat'));
p_bot_onlyt = build_p_from_mat(fullfile(pol_dir, 'Counterfactual_to_compare_policies_bottom_onlyt.mat'));
p_top_onlyt = build_p_from_mat(fullfile(pol_dir, 'Counterfactual_to_compare_policies_top_onlyt.mat'));
p_nobasef   = build_p_from_mat(fullfile(pol_dir, 'Counterfactual_to_compare_policies_nobasef.mat'));

% Helper: extract Change column (col 1 in the 3-column Tab) by row name

ch = @(T, name) T{name, 1};

% Helper: extract CF and Initial equil values (cols 2 and 3)

cf_eq   = @(T, name) T{name, 2};
init_eq = @(T, name) T{name, 3};

% Helper: total immigrant employment % change = ((imm_T_CF + imm_NT_CF) -

imm_total_pct = @(T) ((cf_eq(T,'emp_imm_T') + cf_eq(T,'emp_imm_NT')) ...
                     - (init_eq(T,'emp_imm_T') + init_eq(T,'emp_imm_NT'))) ...
                     / (init_eq(T,'emp_imm_T') + init_eq(T,'emp_imm_NT')) * 100;

% Format a percentage (already in %) with 2 decimals 

fpct = @(x) sprintf('%.2f\\%%', x);

%% =============================================================
%  Table 1 — 14 SMM-calibrated parameters (Sec 5.4)
%  =============================================================

fid = fopen(fullfile(tables_out, 'table1.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcc lcc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, 'Parameter description & Parameter & Estimate & Parameter description & Parameter & Estimate \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Share of natives, T              & $\\beta_T$              & %.2f     & Covariance of $\\psi$ and $f_j$, NT & $\\sigma_{\\psi,f,NT}$ & %.2f \\\\\n', PP_cal.beta,        PP_cal.cov_psif_nt);
fprintf(fid, 'Share of natives, NT             & $\\beta_{NT}$           & %.2f     & Fixed cost of immigrants, T        & $f_{imm,T}$          & %.2E \\\\\n', PP_cal.beta_nt,     PP_cal.f_imm);
fprintf(fid, 'Dispersion in $\\psi_j$, T        & $\\sigma_{\\psi,T}$      & %.2f     & Fixed cost of immigrants, NT       & $f_{imm,NT}$         & %.4f \\\\\n', PP_cal.sigma_psi,   PP_cal.f_imm_nt);
fprintf(fid, 'Dispersion in $\\psi_j$, NT       & $\\sigma_{\\psi,NT}$     & %.2f     & Productivity in RoW                & $\\psi_x$             & %.2f \\\\\n', PP_cal.sigma_psi_nt, PP_cal.mu_psix);
fprintf(fid, 'Dispersion in $f_j$, T           & $\\sigma_{f,T}$         & %.0f    & Fixed cost of exporting            & $f_g$                & %.3f \\\\\n', PP_cal.sigma_f,     PP_cal.f_g);
fprintf(fid, 'Dispersion in $f_j$, NT          & $\\sigma_{f,NT}$        & %.0f    & Iceberg trade cost                 & $\\tau$               & %.2f \\\\\n', PP_cal.sigma_f_nt,  PP_cal.taugx);
fprintf(fid, 'Covariance of $\\psi$ and $f_j$, T & $\\sigma_{\\psi,f,T}$    & %.2f   & Elasticity $s_j$ to $n$            & $\\iota$              & %.3f \\\\\n', PP_cal.cov_psif,    PP_cal.iota);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'table1.tex'));

%% =============================================================
%  Table 2 — Welfare effects with and without firm heterogeneity
%  =============================================================

% Real-earnings-natives values 

he_o = ch(h_open,'earn_p');     % heterog open
he_c = ch(h_closed,'earn_p');   % heterog closed (autarky)
ho_o = ch(m_open,'earn_p');     % homog open
ho_c = ch(m_closed,'earn_p');   % homog closed (autarky)

ratio_autarky_open_heterog = round(he_c, 3) / round(he_o, 3);          
ratio_homog_heterog_open   = round(ho_o, 3) / round(he_o, 3) * 100;    

fid = fopen(fullfile(tables_out, 'table2.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lccc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Open to Trade & Trade Autarky & Autarky/Open \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Heterogeneous $s_j$             & %.3f\\%% & %.3f\\%% & %.2f\\%% \\\\\n', he_o, he_c, ratio_autarky_open_heterog);
fprintf(fid, 'Homogeneous within-sector $s_j$ & %.3f\\%% & %.3f\\%% &           \\\\\n', ho_o, ho_c);
fprintf(fid, 'Homogeneous/Heterogeneous       & %.0f\\%%   &              &           \\\\\n', ratio_homog_heterog_open);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'table2.tex'));

%% =============================================================
%  Sec 6.1 aggregates in-text
%  =============================================================

ne_p  = ch(h_open,'earn_p');       % native real earnings
fo_p  = ch(h_open,'prof_p');       % firm-owner welfare (profits)
ti_p  = ch(h_open,'income_real');  % total income (workers + profits)

fid = fopen(fullfile(tables_out, 'sec61_aggregates.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Welfare change \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Native workers       & %.3f\\%% \\\\\n', ne_p);
fprintf(fid, 'Firm owners          & %.3f\\%% \\\\\n', fo_p);
fprintf(fid, 'Total income         & %.3f\\%% \\\\\n', ti_p);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'sec61_aggregates.tex'));

%% =============================================================
%  Sec 6.1 dollar gains — monetary conversion to 2019 USD PPP
%  Reuses the three percentages already computed for sec61_aggregates
%  (ne_p, fo_p, ti_p) and scales them by OECD constants for Germany
%  2019 to recover dollar-amount gains.
%
%  Four OECD constants drive the dollar-amount conversion, hardcoded
%  here for reproducibility:
%
%  Constant                                     | Value
%  ---------------------------------------------+---------------
%  per-worker wage (constant 2019 USD PPP)      |   46,838
%  GDP (mn, current 2019 USD PPP)               |  4,928,323.5
%  Dependent employees (thousand)               |     41,145
%  Markup (aggregate, model output)             |      3.0833
%
%  Unit note: OECD's AV_AN_WAGE is published as REAL average annual wages
%  (constant prices); EO 2020 Table N is labelled "Real average annual
%  wages ... 2019 USD PPP".
%  OECD's National-Accounts GDP series above is published in current
%  2019 USD PPP for the year 2019. For 2019 itself, "constant 2019" and
%  "current 2019" coincide (the deflator at the base year is 1).
%
%  Per-worker wage derivation: OECD's AV_AN_WAGE is per-FTE; the model maps
%  to a per-worker concept (each LIAB worker is one person, not one FTE), so
%  the per-FTE value is divided by the FT-hours / all-employee-hours ratio:
%
%    Step                                                       | Value
%    -----------------------------------------------------------+--------
%    OECD EO 2020 Table N (per-FTE, real, constant 2019 USD PPP)| 53,638
%    ÷ FT-hours / all-hours ratio (39.43 / 34.432 = 1.1452)     | ÷ 1.1452
%    = per-worker average wage (real, constant 2019 USD PPP)    | = 46,838
%  ========================================================================

% Fractional changes (ne_p, fo_p, ti_p are already in percent)

earn_p_ch        = ne_p / 100;
prof_p_ch        = fo_p / 100;
total_income_ch  = ti_p / 100;

% Initial-equilibrium employment counts: needed to derive the immigrant
% share of the labor force. Loaded directly from the heterog-open .mat
% workspace since the h_open table only stores percentage changes.

W61 = load(fullfile(pkg_root, ...
        'code/model/heterogeneous/Results_counterfactuals/Counterfactual_heterogeneous_open.mat'), ...
        'main_aggregates_0');
Limm_count_0    = W61.main_aggregates_0(10);
Limm_nt_count_0 = W61.main_aggregates_0(11);
Ld_count_0      = W61.main_aggregates_0(13);
Ld_nt_count_0   = W61.main_aggregates_0(14);

AVG_WAGE_PPP_USD       = 46838;        % OECD per-worker wage DE 2019, 2019 USD PPP (see derivation above)
LF_TOTAL_THOUSAND      = 41145;        % OECD National Accounts dependent employees (SAL), DE 2019
GDP_USDPPP_MN          = 4928323.5;    % OECD GDP DE 2019, current 2019 USD PPP (millions)
MARKUP_AGGREGATE       = 3.1 ;         % Model aggregate markup

% Immigrant share from the model's initial-equilibrium employment counts
imm_total_count = Limm_count_0 + Limm_nt_count_0;
nat_total_count = Ld_count_0   + Ld_nt_count_0;
immigrant_share = imm_total_count / (imm_total_count + nat_total_count);

% Convert OECD inputs from thousand/million to absolute persons / dollars
LF_TOTAL          = LF_TOTAL_THOUSAND * 1e3;           % persons
NATIVE_LF         = LF_TOTAL * (1 - immigrant_share);  % persons
GDP_USDPPP        = GDP_USDPPP_MN * 1e6;               % dollars
PROFIT_INCOME_USD = GDP_USDPPP / MARKUP_AGGREGATE;     % aggregate profit income, dollars

% Dollar-amount conversion
native_gain_USD       = AVG_WAGE_PPP_USD * NATIVE_LF * earn_p_ch;
firm_owner_gain_USD   = PROFIT_INCOME_USD            * prof_p_ch;
total_income_gain_USD = native_gain_USD + firm_owner_gain_USD;

fid = fopen(fullfile(tables_out, 'sec61_dollar_gains.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Welfare change (\\%%) & USD (2019, PPP, billions) \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Native workers   & %.3f\\%% & \\$%.1f \\\\\n', earn_p_ch*100,       native_gain_USD/1e9);
fprintf(fid, 'Firm owners      & %.3f\\%% & \\$%.1f \\\\\n', prof_p_ch*100,       firm_owner_gain_USD/1e9);
fprintf(fid, 'Total income     & %.3f\\%% & \\$%.1f \\\\\n', total_income_ch*100, total_income_gain_USD/1e9);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'sec61_dollar_gains.tex'));

%% =============================================================
%  Sec 6.3 dampening decomposition (in Table 2)
%  =============================================================

gap_heterog        = he_c - he_o;                 % total dampening from openness, heterog model
gap_homog          = ho_c - ho_o;                 % terms-of-trade dampening (homog)
gap_heterogeneity  = gap_heterog - gap_homog;     % heterogeneity-driven residual
share_tot          = gap_homog        / gap_heterog * 100;  %  of total dampening from ToT
share_het          = gap_heterogeneity / gap_heterog * 100;  % from heterogeneity
ratio_closed_open  = gap_heterog / he_o * 100;    % closed/open percentage gap

fid = fopen(fullfile(tables_out, 'sec63_decomposition.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Change (pp) & Share of total dampening \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Closed vs.\\ open (heterogeneous) & %.3f & %.0f\\%% larger \\\\\n', gap_heterog, ratio_closed_open);
fprintf(fid, 'Terms-of-trade dampening         & %.3f & %.0f\\%% \\\\\n',         gap_homog, share_tot);
fprintf(fid, 'Heterogeneity-driven dampening   & %.3f & %.0f\\%% \\\\\n',         gap_heterogeneity, share_het);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'sec63_decomposition.tex'));

%% =============================================================
%  Table C.7 — Simulated vs data moments (Appendix C)
%  =============================================================

fid = fopen(fullfile(tables_out, 'tableC7.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcc lcc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, 'Moment description & Simulated & Data & Moment description & Simulated & Data \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Aggregate $s_T$                                      & %.2f  & %.2f  & $E(1-s_{j,p90})-E(1-s_{j,p50})$, NT  & %.3f & %.3f \\\\\n', Mom_Model.sagg,                Mom_Data.sagg,                Mom_Model.moment_correlation_nt, Mom_Data.moment_correlation_nt);
fprintf(fid, 'Aggregate $s_{NT}$                                   & %.2f  & %.2f  & Share of firms hiring immigrants, T  & %.2f & %.2f \\\\\n', Mom_Model.sagg_nt,             Mom_Data.sagg_nt,             Mom_Model.mean_Dimm,             Mom_Data.mean_Dimm);
fprintf(fid, '$Var(\\log(rev_j) \\mid s_j,\\text{exp}_j)$, T          & %.2f  & %.2f  & Share of firms hiring immigrants, NT & %.2f & %.2f \\\\\n', Mom_Model.std_l_rev_cond,      Mom_Data.std_l_rev_cond,      Mom_Model.mean_Dimm_nt,          Mom_Data.mean_Dimm_nt);
fprintf(fid, '$Var(\\log(rev_j) \\mid s_j)$, NT                      & %.2f  & %.2f  & GDP per capita RoW to Germany        & %.2f & %.2f \\\\\n', Mom_Model.std_l_rev_nt_cond,   Mom_Data.std_l_rev_nt_cond,   Mom_Model.GDP_RoW_Ger,           Mom_Data.GDP_RoW_Ger);
fprintf(fid, '$Var((1-s_j)/s_j)$, T                                & %.2f  & %.2f  & Share of firms exporting, T          & %.2f & %.2f \\\\\n', Mom_Model.std_l_sd_ratio,      Mom_Data.std_l_sd_ratio,      Mom_Model.mean_Dexp,             Mom_Data.mean_Dexp);
fprintf(fid, '$Var((1-s_j)/s_j)$, NT                               & %.2f  & %.2f  & $E$(Export to Domestic $Rev_j$), T   & %.2f & %.2f \\\\\n', Mom_Model.std_l_sd_ratio_nt,   Mom_Data.std_l_sd_ratio_nt,   Mom_Model.moment_tau,            Mom_Data.moment_tau);
fprintf(fid, '$E(1-s_{j,p90})-E(1-s_{j,p50})$, T                   & %.3f & %.3f & $E(s_j)$                              & %.2f & %.2f \\\\\n', Mom_Model.moment_correlation,  Mom_Data.moment_correlation,  Mom_Model.mean_sd,               Mom_Data.mean_sd);
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'tableC7.tex'));

%% =============================================================
%  Table D1 — Heterogeneous open: employment & wages by sector 
%  =============================================================

fid = fopen(fullfile(tables_out, 'tableD1.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcccc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & \\multicolumn{2}{c}{Labor units} & \\multicolumn{2}{c}{Effective units} \\\\\n');
fprintf(fid, '\\cmidrule(lr){2-3} \\cmidrule(lr){4-5}\n');
fprintf(fid, ' & Tradable & Non-Tradable & Tradable & Non-Tradable \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{5}{l}{\\textbf{Employment}} \\\\\n');
fprintf(fid, 'Total     & %s & %s & %s & %s \\\\\n', fpct(ch(h_open,'emp_T')),       fpct(ch(h_open,'emp_NT')),       fpct(ch(h_open,'emp_eff_T')),       fpct(ch(h_open,'emp_eff_NT')));
fprintf(fid, 'Native    & %s & %s & %s & %s \\\\\n', fpct(ch(h_open,'emp_nat_T')),   fpct(ch(h_open,'emp_nat_NT')),   fpct(ch(h_open,'emp_eff_nat_T')),   fpct(ch(h_open,'emp_eff_nat_NT')));
fprintf(fid, 'Immigrant & %s & %s & %s & %s \\\\\n', fpct(ch(h_open,'emp_imm_T')),   fpct(ch(h_open,'emp_imm_NT')),   fpct(ch(h_open,'emp_eff_imm_T')),   fpct(ch(h_open,'emp_eff_imm_NT')));
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{5}{l}{\\textbf{Wages (relative to numeraire)}} \\\\\n');
fprintf(fid, 'Natives    & %s & %s & %s & %s \\\\\n', fpct(ch(h_open,'earn_T')),       fpct(ch(h_open,'earn_NT')),       fpct(ch(h_open,'w_T')),     fpct(ch(h_open,'w_NT')));
fprintf(fid, 'Immigrants & %s & %s & %s & %s \\\\\n', fpct(ch(h_open,'earn_T_imm_ch')), fpct(ch(h_open,'earn_NT_imm_ch')), fpct(ch(h_open,'w_imm_T')), fpct(ch(h_open,'w_imm_NT')));
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'tableD1.tex'));

%% =============================================================
%  Table D2 — 4 policies
%  =============================================================

fid = fopen(fullfile(tables_out, 'tableD2.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lcccc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Policy 1 & Policy 2 & Policy 3 & Policy 4 \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Real Earnings Natives & %s & %s & %s & %s \\\\\n', ...
    fpct(ch(p_basef,'earn_p')), fpct(ch(p_top10,'earn_p')), fpct(ch(p_bot_onlyt,'earn_p')), fpct(ch(p_top_onlyt,'earn_p')));
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{5}{l}{\\textit{Real Wages per efficiency units}} \\\\\n');
for nm = {'w_T_p', 'w_NT_p', 'w_imm_T_p', 'w_imm_NT_p'}
    label = struct('w_T_p','Natives - T','w_NT_p','Natives - NT','w_imm_T_p','Immigrants - T','w_imm_NT_p','Immigrants - NT');
    fprintf(fid, '%s & %s & %s & %s & %s \\\\\n', label.(nm{1}), ...
        fpct(ch(p_basef,nm{1})), fpct(ch(p_top10,nm{1})), fpct(ch(p_bot_onlyt,nm{1})), fpct(ch(p_top_onlyt,nm{1})));
end
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{5}{l}{\\textit{Employment}} \\\\\n');
for nm = {'emp_nat_T', 'emp_nat_NT', 'emp_imm_T', 'emp_imm_NT'}
    label = struct('emp_nat_T','Natives - T','emp_nat_NT','Natives - NT','emp_imm_T','Immigrants - T','emp_imm_NT','Immigrants - NT');
    fprintf(fid, '%s & %s & %s & %s & %s \\\\\n', label.(nm{1}), ...
        fpct(ch(p_basef,nm{1})), fpct(ch(p_top10,nm{1})), fpct(ch(p_bot_onlyt,nm{1})), fpct(ch(p_top_onlyt,nm{1})));
end
fprintf(fid, 'Immigrants & %s & %s & %s & %s \\\\\n', ...
    fpct(imm_total_pct(p_basef)), fpct(imm_total_pct(p_top10)), fpct(imm_total_pct(p_bot_onlyt)), fpct(imm_total_pct(p_top_onlyt)));
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'tableD2.tex'));

%% =============================================================
%  Table D3 — Single policy (nobasef)
%  =============================================================

fid = fopen(fullfile(tables_out, 'tableD3.tex'), 'w');
fprintf(fid, '%% Auto-generated by Export_latex_tables.m\n');
fprintf(fid, '\\begin{tabular}{lc}\n');
fprintf(fid, '\\toprule\n');
fprintf(fid, ' & Removing cost to begin hiring immigrants \\\\\n');
fprintf(fid, '\\midrule\n');
fprintf(fid, 'Real Earnings Natives & %s \\\\\n', fpct(ch(p_nobasef,'earn_p')));
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{2}{l}{\\textit{Real Wages}} \\\\\n');
fprintf(fid, 'Natives - T     & %s \\\\\n', fpct(ch(p_nobasef,'w_T_p')));
fprintf(fid, 'Natives - NT    & %s \\\\\n', fpct(ch(p_nobasef,'w_NT_p')));
fprintf(fid, 'Immigrants - T  & %s \\\\\n', fpct(ch(p_nobasef,'w_imm_T_p')));
fprintf(fid, 'Immigrants - NT & %s \\\\\n', fpct(ch(p_nobasef,'w_imm_NT_p')));
fprintf(fid, '\\midrule\n');
fprintf(fid, '\\multicolumn{2}{l}{\\textit{Employment}} \\\\\n');
fprintf(fid, 'Natives - T     & %s \\\\\n', fpct(ch(p_nobasef,'emp_nat_T')));
fprintf(fid, 'Natives - NT    & %s \\\\\n', fpct(ch(p_nobasef,'emp_nat_NT')));
fprintf(fid, 'Immigrants - T  & %s \\\\\n', fpct(ch(p_nobasef,'emp_imm_T')));
fprintf(fid, 'Immigrants - NT & %s \\\\\n', fpct(ch(p_nobasef,'emp_imm_NT')));
fprintf(fid, '\\bottomrule\n');
fprintf(fid, '\\end{tabular}\n');
fclose(fid);
fprintf('Wrote %s\n', fullfile(tables_out, 'tableD3.tex'));

fprintf('\nAll LaTeX tables written to %s\n', tables_out);


% =============================================================
% Local function: build_h_open_from_mat
% Loads the raw equilibrium objects persisted by
% Counterfactual_heterogeneous_open.m and returns a 1-column table whose
% row names match the labels this script uses via ch(h_open, name).
% Stored values are percentage changes.
% =============================================================

function T = build_h_open_from_mat(mat_path)
    W = load(mat_path, 'x_sol_0', 'x_sol', 'main_aggregates_0', ...
                       'main_aggregates', 'PP');

    % --- Unpack the elements needed (indexing matches equilLoop outputs) ---
    wd_0 = 1;  wd = 1;
    wx_0      = W.x_sol_0(1);   wx      = W.x_sol(1);
    Pd_0      = W.x_sol_0(2);   Pd      = W.x_sol(2);
    wimm_0    = W.x_sol_0(4);   wimm    = W.x_sol(4);
    wd_nt_0   = W.x_sol_0(7);   wd_nt   = W.x_sol(7);
    wimm_nt_0 = W.x_sol_0(8);   wimm_nt = W.x_sol(8);
    Pd_nt_0   = W.x_sol_0(9);   Pd_nt   = W.x_sol(9);

    Ld_alt_0      = W.main_aggregates_0(5);    Ld_alt    = W.main_aggregates(5);
    I_alt_0       = W.main_aggregates_0(6);    I_alt     = W.main_aggregates(6);
    Ld_alt_nt_0   = W.main_aggregates_0(7);    Ld_alt_nt = W.main_aggregates(7);
    I_alt_nt_0    = W.main_aggregates_0(8);    I_alt_nt  = W.main_aggregates(8);
    Limm_count_0    = W.main_aggregates_0(10); Limm_count    = W.main_aggregates(10);
    Limm_nt_count_0 = W.main_aggregates_0(11); Limm_nt_count = W.main_aggregates(11);
    Ld_count_0      = W.main_aggregates_0(13); Ld_count      = W.main_aggregates(13);
    Ld_nt_count_0   = W.main_aggregates_0(14); Ld_nt_count   = W.main_aggregates(14);
    rev_t_0   = W.main_aggregates_0(16);       rev_t  = W.main_aggregates(16);
    rev_nt_0  = W.main_aggregates_0(17);       rev_nt = W.main_aggregates(17);

    alpha = W.PP.alpha;

    % --- Numeraire (ratio against export wage) ---
    norm_0 = wx_0;
    norm   = wx;

    % --- CES price index ---
    p_0 = ((Pd_0/(1-alpha))^(1-alpha) * (Pd_nt_0/alpha)^alpha) / norm_0;
    p   = ((Pd  /(1-alpha))^(1-alpha) * (Pd_nt  /alpha)^alpha) / norm;

    % --- Real native earnings (welfare measure for natives) ---
    earn_0 = ((Ld_alt_0*wd_0 + Ld_alt_nt_0*wd_nt_0) / (Ld_count_0 + Ld_nt_count_0)) / norm_0;
    earn   = ((Ld_alt  *wd   + Ld_alt_nt  *wd_nt  ) / (Ld_count   + Ld_nt_count  )) / norm;
    earn_p_ch = (earn/p) / (earn_0/p_0) - 1;

    % --- Real firm-owner welfare (profits / price index). PP_0.pid and
    % pid_nt are stored at positions 5 and 10 of x_sol. ---
    pid_0     = W.x_sol_0(5);   pid     = W.x_sol(5);
    pid_nt_0  = W.x_sol_0(10);  pid_nt  = W.x_sol(10);
    prof_0 = (pid_0 + pid_nt_0) / norm_0;
    prof   = (pid   + pid_nt  ) / norm;
    prof_p_ch = (prof/p) / (prof_0/p_0) - 1;

    % --- Real total income (revenues / price index) ---
    total_income_real_0 = ((rev_t_0 + rev_nt_0) / norm_0) / p_0;
    total_income_real   = ((rev_t   + rev_nt  ) / norm  ) / p;
    income_real_ch = total_income_real / total_income_real_0 - 1;

    % --- Sectoral employment (% changes; head-count and effective units) ---
    emp_T_ch          = ((Limm_count    + Ld_count   ) / (Limm_count_0    + Ld_count_0   )) - 1;
    emp_NT_ch         = ((Limm_nt_count + Ld_nt_count) / (Limm_nt_count_0 + Ld_nt_count_0)) - 1;
    emp_nat_T_ch      =  Ld_count    / Ld_count_0    - 1;
    emp_nat_NT_ch     =  Ld_nt_count / Ld_nt_count_0 - 1;
    emp_imm_T_ch      =  Limm_count    / Limm_count_0    - 1;
    emp_imm_NT_ch     =  Limm_nt_count / Limm_nt_count_0 - 1;
    emp_eff_T_ch      = ((I_alt    + Ld_alt   ) / (I_alt_0    + Ld_alt_0   )) - 1;
    emp_eff_NT_ch     = ((I_alt_nt + Ld_alt_nt) / (I_alt_nt_0 + Ld_alt_nt_0)) - 1;
    emp_eff_nat_T_ch  =  Ld_alt    / Ld_alt_0    - 1;
    emp_eff_nat_NT_ch =  Ld_alt_nt / Ld_alt_nt_0 - 1;
    emp_eff_imm_T_ch  =  I_alt    / I_alt_0    - 1;
    emp_eff_imm_NT_ch =  I_alt_nt / I_alt_nt_0 - 1;

    % --- Wages (labor units = earn_T/NT per native head; effective units
    % = w_T/NT and w_imm_T/NT per effective unit) ---
    earn_T_0 = ((Ld_alt_0*wd_0)/Ld_count_0)/norm_0;
    earn_T   = ((Ld_alt  *wd  )/Ld_count  )/norm;
    earn_NT_0 = ((Ld_alt_nt_0*wd_nt_0)/Ld_nt_count_0)/norm_0;
    earn_NT   = ((Ld_alt_nt  *wd_nt  )/Ld_nt_count  )/norm;
    earn_T_ch  = earn_T  / earn_T_0  - 1;
    earn_NT_ch = earn_NT / earn_NT_0 - 1;

    w_T_ch        = (wd     /norm) / (wd_0     /norm_0) - 1;
    w_NT_ch       = (wd_nt  /norm) / (wd_nt_0  /norm_0) - 1;
    w_imm_T_ch    = (wimm   /norm) / (wimm_0   /norm_0) - 1;
    w_imm_NT_ch   = (wimm_nt/norm) / (wimm_nt_0/norm_0) - 1;

    % Immigrant per-head earnings (labor units, using native wage rate × effective units)
    earn_T_imm_0  = ((I_alt_0   *wd_0  )/Limm_count_0   )/norm_0;
    earn_T_imm    = ((I_alt     *wd    )/Limm_count     )/norm;
    earn_NT_imm_0 = ((I_alt_nt_0*wd_nt_0)/Limm_nt_count_0)/norm_0;
    earn_NT_imm   = ((I_alt_nt  *wd_nt  )/Limm_nt_count  )/norm;
    earn_T_imm_ch  = earn_T_imm  / earn_T_imm_0  - 1;
    earn_NT_imm_ch = earn_NT_imm / earn_NT_imm_0 - 1;

    % --- Bundle as a 1-column table indexed by the row names this script reads ---
    names = { ...
        'earn_p'; 'prof_p'; 'income_real'; ...
        'emp_T'; 'emp_NT'; 'emp_eff_T'; 'emp_eff_NT'; ...
        'emp_nat_T'; 'emp_nat_NT'; 'emp_eff_nat_T'; 'emp_eff_nat_NT'; ...
        'emp_imm_T'; 'emp_imm_NT'; 'emp_eff_imm_T'; 'emp_eff_imm_NT'; ...
        'earn_T'; 'earn_NT'; 'w_T'; 'w_NT'; ...
        'earn_T_imm_ch'; 'earn_NT_imm_ch'; 'w_imm_T'; 'w_imm_NT'};
    vals = 100 * [ ...
        earn_p_ch; prof_p_ch; income_real_ch; ...
        emp_T_ch; emp_NT_ch; emp_eff_T_ch; emp_eff_NT_ch; ...
        emp_nat_T_ch; emp_nat_NT_ch; emp_eff_nat_T_ch; emp_eff_nat_NT_ch; ...
        emp_imm_T_ch; emp_imm_NT_ch; emp_eff_imm_T_ch; emp_eff_imm_NT_ch; ...
        earn_T_ch; earn_NT_ch; w_T_ch; w_NT_ch; ...
        earn_T_imm_ch; earn_NT_imm_ch; w_imm_T_ch; w_imm_NT_ch];
    T = table(vals, 'VariableNames', {'Change'}, 'RowNames', names);
end

% =============================================================
% Local function: build_h_closed_from_mat
% Loads the raw equilibrium objects persisted by
% Counterfactual_heterogeneous_closed.m and returns a 1-row table whose
% only entry is earn_p (% change in real native earnings). That is the
% only h_closed row this script uses.Logic mirrors the open helper exactly.
% =============================================================

function T = build_h_closed_from_mat(mat_path)
    W = load(mat_path, 'x_sol_0', 'x_sol', 'main_aggregates_0', ...
                       'main_aggregates', 'PP');

    wd_0 = 1; wd = 1;
    wx_0      = W.x_sol_0(1);   wx      = W.x_sol(1);
    Pd_0      = W.x_sol_0(2);   Pd      = W.x_sol(2);
    wd_nt_0   = W.x_sol_0(7);   wd_nt   = W.x_sol(7);
    Pd_nt_0   = W.x_sol_0(9);   Pd_nt   = W.x_sol(9);

    Ld_alt_0    = W.main_aggregates_0(5);    Ld_alt    = W.main_aggregates(5);
    Ld_alt_nt_0 = W.main_aggregates_0(7);    Ld_alt_nt = W.main_aggregates(7);
    Ld_count_0    = W.main_aggregates_0(13); Ld_count    = W.main_aggregates(13);
    Ld_nt_count_0 = W.main_aggregates_0(14); Ld_nt_count = W.main_aggregates(14);

    alpha = W.PP.alpha;
    norm_0 = wx_0;
    norm   = wx;

    p_0 = ((Pd_0/(1-alpha))^(1-alpha) * (Pd_nt_0/alpha)^alpha) / norm_0;
    p   = ((Pd  /(1-alpha))^(1-alpha) * (Pd_nt  /alpha)^alpha) / norm;

    earn_0 = ((Ld_alt_0*wd_0 + Ld_alt_nt_0*wd_nt_0) / (Ld_count_0 + Ld_nt_count_0)) / norm_0;
    earn   = ((Ld_alt  *wd   + Ld_alt_nt  *wd_nt  ) / (Ld_count   + Ld_nt_count  )) / norm;
    earn_p_ch = (earn/p) / (earn_0/p_0) - 1;

    T = table(100*earn_p_ch, 'VariableNames', {'Change'}, 'RowNames', {'earn_p'});
end

% =============================================================
% Local function: build_m_open_from_mat
% Loads the raw equilibrium objects persisted by
% Counterfactual_homogeneous_open.m and returns a 1-row table whose only
% entry is earn_p (% change in real native earnings, homogeneous open
% economy). Used for the Table 2 col 1 row 2 entry and the
% sec63_decomposition.tex terms-of-trade row.
% =============================================================

function T = build_m_open_from_mat(mat_path)
    T = compute_earn_p_table(mat_path);
end

% =============================================================
% Local function: build_m_closed_from_mat
% Same as build_m_open_from_mat but for the homogeneous closed-economy
% equilibrium.
% =============================================================
function T = build_m_closed_from_mat(mat_path)
    T = compute_earn_p_table(mat_path);
end

% =============================================================
% Shared kernel for the three earn_p-only helpers (h_closed, m_open,
% m_closed). Loads the raw equilibrium objects and returns a 1-row table
% with the percentage change in real native earnings.
% =============================================================
function T = compute_earn_p_table(mat_path)
    W = load(mat_path, 'x_sol_0', 'x_sol', 'main_aggregates_0', ...
                       'main_aggregates', 'PP');

    wd_0 = 1; wd = 1;
    wx_0      = W.x_sol_0(1);   wx      = W.x_sol(1);
    Pd_0      = W.x_sol_0(2);   Pd      = W.x_sol(2);
    wd_nt_0   = W.x_sol_0(7);   wd_nt   = W.x_sol(7);
    Pd_nt_0   = W.x_sol_0(9);   Pd_nt   = W.x_sol(9);

    Ld_alt_0    = W.main_aggregates_0(5);    Ld_alt    = W.main_aggregates(5);
    Ld_alt_nt_0 = W.main_aggregates_0(7);    Ld_alt_nt = W.main_aggregates(7);
    Ld_count_0    = W.main_aggregates_0(13); Ld_count    = W.main_aggregates(13);
    Ld_nt_count_0 = W.main_aggregates_0(14); Ld_nt_count = W.main_aggregates(14);

    alpha  = W.PP.alpha;
    norm_0 = wx_0;
    norm   = wx;

    p_0 = ((Pd_0/(1-alpha))^(1-alpha) * (Pd_nt_0/alpha)^alpha) / norm_0;
    p   = ((Pd  /(1-alpha))^(1-alpha) * (Pd_nt  /alpha)^alpha) / norm;

    earn_0 = ((Ld_alt_0*wd_0 + Ld_alt_nt_0*wd_nt_0) / (Ld_count_0 + Ld_nt_count_0)) / norm_0;
    earn   = ((Ld_alt  *wd   + Ld_alt_nt  *wd_nt  ) / (Ld_count   + Ld_nt_count  )) / norm;
    earn_p_ch = (earn/p) / (earn_0/p_0) - 1;

    T = table(100*earn_p_ch, 'VariableNames', {'Change'}, 'RowNames', {'earn_p'});
end

%% =============================================================
% Local function: build_p_from_mat
% Loads the raw equilibrium objects persisted by one policy variant of
% Counterfactual_to_compare_policies.m and returns a 3-column table with
% the 9 scalars used by tableD2.tex / tableD3.tex:
%   earn_p, w_T_p, w_NT_p, w_imm_T_p, w_imm_NT_p,
%   emp_nat_T, emp_nat_NT, emp_imm_T, emp_imm_NT.
% Columns: Change (% change), CF equil value, Initial equil value.
% =============================================================

function T = build_p_from_mat(mat_path)
    W = load(mat_path, 'x_sol_0', 'x_sol', 'main_aggregates_0', ...
                       'main_aggregates', 'PP');

    wd_0 = 1; wd = 1;
    wx_0      = W.x_sol_0(1);   wx      = W.x_sol(1);
    Pd_0      = W.x_sol_0(2);   Pd      = W.x_sol(2);
    wimm_0    = W.x_sol_0(4);   wimm    = W.x_sol(4);
    wd_nt_0   = W.x_sol_0(7);   wd_nt   = W.x_sol(7);
    wimm_nt_0 = W.x_sol_0(8);   wimm_nt = W.x_sol(8);
    Pd_nt_0   = W.x_sol_0(9);   Pd_nt   = W.x_sol(9);

    Ld_alt_0    = W.main_aggregates_0(5);    Ld_alt    = W.main_aggregates(5);
    Ld_alt_nt_0 = W.main_aggregates_0(7);    Ld_alt_nt = W.main_aggregates(7);
    Limm_count_0    = W.main_aggregates_0(10); Limm_count    = W.main_aggregates(10);
    Limm_nt_count_0 = W.main_aggregates_0(11); Limm_nt_count = W.main_aggregates(11);
    Ld_count_0      = W.main_aggregates_0(13); Ld_count      = W.main_aggregates(13);
    Ld_nt_count_0   = W.main_aggregates_0(14); Ld_nt_count   = W.main_aggregates(14);

    alpha  = W.PP.alpha;
    norm_0 = wx_0;
    norm   = wx;

    p_0 = ((Pd_0/(1-alpha))^(1-alpha) * (Pd_nt_0/alpha)^alpha) / norm_0;
    p   = ((Pd  /(1-alpha))^(1-alpha) * (Pd_nt  /alpha)^alpha) / norm;

    earn_0   = ((Ld_alt_0*wd_0 + Ld_alt_nt_0*wd_nt_0) / (Ld_count_0 + Ld_nt_count_0)) / norm_0;
    earn     = ((Ld_alt  *wd   + Ld_alt_nt  *wd_nt  ) / (Ld_count   + Ld_nt_count  )) / norm;
    earn_p_0 = earn_0 / p_0;
    earn_p   = earn   / p;

    w_T_p_0      = (wd_0     / norm_0) / p_0;   w_T_p      = (wd     / norm) / p;
    w_NT_p_0     = (wd_nt_0  / norm_0) / p_0;   w_NT_p     = (wd_nt  / norm) / p;
    w_imm_T_p_0  = (wimm_0   / norm_0) / p_0;   w_imm_T_p  = (wimm   / norm) / p;
    w_imm_NT_p_0 = (wimm_nt_0/ norm_0) / p_0;   w_imm_NT_p = (wimm_nt/ norm) / p;

    emp_nat_T_0  = Ld_count_0;      emp_nat_T  = Ld_count;
    emp_nat_NT_0 = Ld_nt_count_0;   emp_nat_NT = Ld_nt_count;
    emp_imm_T_0  = Limm_count_0;    emp_imm_T  = Limm_count;
    emp_imm_NT_0 = Limm_nt_count_0; emp_imm_NT = Limm_nt_count;

    names = {'earn_p'; 'w_T_p'; 'w_NT_p'; 'w_imm_T_p'; 'w_imm_NT_p'; ...
             'emp_nat_T'; 'emp_nat_NT'; 'emp_imm_T'; 'emp_imm_NT'};
    change_col = 100 * [ ...
        earn_p/earn_p_0         - 1; ...
        w_T_p/w_T_p_0           - 1; ...
        w_NT_p/w_NT_p_0         - 1; ...
        w_imm_T_p/w_imm_T_p_0   - 1; ...
        w_imm_NT_p/w_imm_NT_p_0 - 1; ...
        emp_nat_T/emp_nat_T_0   - 1; ...
        emp_nat_NT/emp_nat_NT_0 - 1; ...
        emp_imm_T/emp_imm_T_0   - 1; ...
        emp_imm_NT/emp_imm_NT_0 - 1];
    cf_col   = [earn_p; w_T_p; w_NT_p; w_imm_T_p; w_imm_NT_p; ...
                emp_nat_T; emp_nat_NT; emp_imm_T; emp_imm_NT];
    init_col = [earn_p_0; w_T_p_0; w_NT_p_0; w_imm_T_p_0; w_imm_NT_p_0; ...
                emp_nat_T_0; emp_nat_NT_0; emp_imm_T_0; emp_imm_NT_0];

    T = table(change_col, cf_col, init_col, ...
              'VariableNames', {'Change','CFequil','Initialequil'}, ...
              'RowNames', names);
end

% =============================================================
% Local function: snapshot_calibration
%
% Returns:
%   Mom_Model  - struct of simulated moments (used by tableC7.tex)
%   Mom_Data   - struct of targeted data moments (Mom_Data_draft in
%                Calibration_Res.m, Section 4)
%   PP_cal     - parameter struct with the calibrated values mapped in
%                (consumed by table1.tex)
% =============================================================

function [Mom_Model, Mom_Data, PP_cal] = snapshot_calibration(pkg_root)

    heterog_dir = fullfile(pkg_root, 'code', 'model', 'heterogeneous');
    orig_dir    = pwd;
    cleanup     = onCleanup(@() cd(orig_dir));

    cd(heterog_dir);
    addpath('Other_functions', 'Equations_equilibrium');

    PP = Setup_PP();

    % Start vector (matches Counterfactual_heterogeneous_open.m's x_0).
    Equil_0 = [0.324335125689298  0.00581557463337634 ...
               0.0112510772006113 0.161173107360179 ...
               360.337575599634   5559.82876523402 ...
               0.876877518299593  0.134468674352483 ...
               0.0131989032931402 189.138983348911];

    % InputVec layout must match the "Read the input vectors" block in
    % Calibration_Res.m.
    InputVec = [PP.taugx;        PP.sigma_psi;   PP.cov_psif;   PP.sigma_f; ...
                PP.beta_nt;      PP.beta;        PP.sigma_psi_nt; PP.cov_psif_nt; ...
                PP.sigma_f_nt;   PP.f_g;         PP.mu_psix;    PP.f_imm; ...
                PP.f_imm_nt;     PP.iota];

    % Calibration_Res declares its own `global Equil_0_last`.
    [~, PP_cal, ExtraDetails, ExitFlag] = Calibration_Res(PP, Equil_0, InputVec);

    if ExitFlag ~= 1
        error('snapshot_calibration: ExitFlag=%d (1 = success). Snapshot failed.', ExitFlag);
    end

    Mom_Model = ExtraDetails.Mom_Model;
    Mom_Data  = ExtraDetails.Mom_Data_draft;
end
